### ISSUE TITLE
Allow manually installed kernels to enable better hardware support

### ISSUE THREAD

**Issue by heuchi** [tuxedocomputers/tuxedo-tomte#12]
Since 8e084d634ea2359d115487085ac5c01c4a6b7602 all other kernel versions are automatically removed from the system.

My problem is this: I have some hardware (USB audio device) that the tuxedo default kernel v5.13.0 doesn't support completely. So I installed a self-compiled v5.16.10 which made that device work a lot better. But two days ago, after having been updated, tomte told me not to shut down the system, because it was updating. It never finished however, and after a forced reboot, the system didn't work anymore. Unfortunately it took me quite some time to realize what had happened: tomte had silently removed the kernel image and modules of the running(!) kernel.

So for now, I had to temporarily deactivate it. Is there a way, to prevent tomte from automatically removing more recent (or manually installed) kernel versions?

**Comment by vinzv** [comment]
`tomte block linux-tuxedo-20.04` should do what you're expecting.

**Comment by heuchi** [comment]
Thanks for pointing out that option.
But wouldn't that have any negative consequences on the standard tuxedo kernel (which is still great to have as a safe option)?
Does the target "linux-tuxedo-20.04" only clean up the remnant kernels?
