### ISSUE TITLE
installing the tuxedo-repos fails in Ubuntu 22.04 due to deprecated apt-key

### ISSUE THREAD

**Issue by enolive** [tuxedocomputers/tuxedo-tomte#15]
after installation of tomte I noticed that installing the tuxedo-repos does not work properly. running `sudo apt update` refuses to read deb.tuxedocomputers.com with a deprecation warning.

It seems that the script is using apt-key for installing the GPG key which is deprecated, see also https://askubuntu.com/questions/1328806/how-to-solve-apt-key-deprecated

Workaround:

1. delete /etc/apt/trusted.gpg
2. download the public key from tuxedo and put it into the /etc/apt/trusted.gpg.d directory. 

`wget -O - https://deb.tuxedocomputers.com/0x54840598.pub.asc  | sudo tee /etc/apt/trusted.gpg.d/tuxedo-computers.asc` 

Note: I am unable to find any info how to import the public key by hand on tuxedo's website. I got the download link to the pub key from google cache.

**Comment by stkr22** [comment]
Thanks for the explanation on how to fix it @enolive.

Facing the same issue. Besides, the secure way to add ppas is by using the signed-by option. This specifies a key for a specific repo. By adding it to the system keyring theoretically packages in other repositories could also be signed by it and ubuntu would accept it.

**Comment by vinzv** [comment]
This should be fixed for a while now, therefore closing this issue.

If you experience any further problems, please feel free to reopen it!
