### ISSUE TITLE
TUXEDO N650DU

### ISSUE THREAD

**Issue by KristjanESPERANTO** [tuxedocomputers/tuxedo-tomte#17]
I try it on a TUXEDO N650DU (Debian 11) and get the following error message:

```bash
~$ sudo tuxedo-tomte list
It seems that this is not a TUXEDO device. Please contact us if this is a mistake
```

**Comment by vinzv** [comment]
Hi... sorry for the long wait!

While you're right that Tomte does not support TUXEDO BC1507 using Tomte on Debian will not work either way. Only Ubuntu flavors and directly based distributions are supported: https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/What-is-TUXEDO-Tomte-.tuxedo

Tomte switches Ubuntu's repo servers to mirrors with our QA. And that makes no sense for a Debian system, of course.

**Comment by KristjanESPERANTO** [comment]
Then the error message is wrong. It should be like this:
`It seems that this is not a supported device. Please contact us if this is a mistake.`
