### ISSUE TITLE
KDE Neon 22.04

### ISSUE THREAD

**Issue by ahornero** [tuxedocomputers/tuxedo-tomte#19]
Hi, could you please add support to KDE Neon 22.04? It is currently only supporting 20.04.

![image](https://user-images.githubusercontent.com/5605168/212955417-69472eec-f1ca-46a9-9427-d206012bc9c4.png)

One workaround for me was to replace KDE Neon string with TUXEDO OS or Ubuntu in the _/etc/os-release_ file, but not very happy to lose the KDE Neon identity in my system, and I am also concerned about consistency. Any thoughts?

Thanks!

**Comment by ashwinvis** [comment]
I opened a PR for this #16

**Comment by vinzv** [comment]
Thanks for bringing this up!

Neon abilities are now available in Tomte via https://github.com/tuxedocomputers/tuxedo-tomte/commit/c4b60722244009f056e21e2e4cf3573020e725e8
