### ISSUE TITLE
Support Ubuntu based OS

### ISSUE THREAD

**Issue by hduelme** [tuxedocomputers/tuxedo-tomte#2]
At the moment OS like Linux Mint are not supported.
By running `tuxedo-tomte` you get  the message:
`Argument "" isn't numeric in numeric le (<=) at /usr/bin/tuxedo-tomte line 4107.
This OS is not supported`

For this the `ID_LIKE` and `UBUNTU_CODENAME` in `/etc/os-release` could be used:
![image](https://user-images.githubusercontent.com/46139144/130945261-56da29ae-23c0-4511-aca6-9e55d1f28b5f.png)

At the moment my workaround is setting the versions manually:
![image](https://user-images.githubusercontent.com/46139144/130946475-dac217b1-917f-4ff7-ba16-5ebf616924c1.png)

**Comment by vinzv** [comment]
Please, don't do that! There is a reason for this check even though Mint is quite close to Ubuntu. Tomte replaces repository URLs and most likely will break your system!

For unsupported distributions you will have to stick with manual installation of the packages: https://www.tuxedocomputers.com/en/Notes-on-the-use-of-operating-systems-that-are-not-officially-supported_1.tuxedo
