### ISSUE TITLE
Support for Pop OS 22.04

### ISSUE THREAD

**Issue by davelbit** [tuxedocomputers/tuxedo-tomte#22]
Hey Tuxedo team,

I'm currently rocking an awesome Infinitybook 16 Pro, Gen-7 running Pop OS 22.04. I've realized after the installation, and especially now after using it for a couple of weeks, that there might be some drivers missing, which affects the performance in some cases. I discovered after some research that that's what tuxedo-tomte is for. However, it seems that tuxedo-tomte does not support Pop OS at this time.

And as I was thinking of potential workaround I was thinking that  both Ubuntu and Pop OS are debian derivatives, which makes it highly unlikely that there will be any software and or driver imcompatibilities (just an assumption). With that in mind, I was wondering if it would be possible to add the following line to the perl script:

`###############################################################################
# find OS name and version and put them into $distribution and
# $distributionVersion
#
sub readOSData {
    my $osReleaseFile = '/etc/os-release';
    my @osReleaseLines;

    @osReleaseLines = readFileReturnLines($osReleaseFile);

    if (!@osReleaseLines) {
        print "Can't determine the operating system\n";
        exit(0);
    }

    foreach (@osReleaseLines) {
        if ($_ =~ /^NAME=/) {
            $_ =~ /NAME=\"(.*)\"/;
            $distribution = $1;
            $distribution =~ s/Pop/Ubuntu/g;  # Replace "Pop" with "Ubuntu"                            # NEW LINE
        }
        if ($_ =~ /^VERSION_ID=/) {
            $_ =~ /VERSION_ID=\"(.*)\"/;
            $distributionVersion = $1;
        }
    }

    $completeDistVersion = $distribution . ' ' . $distributionVersion;

    # Check if the distribution is supported
    if (!grep { $_ eq $distribution } @supportedDistros) {
        print "Distribution '$distribution' not supported\n";
        exit(0);
    }
}`

Which essentially makes it so, that "Pop" distro name will be changed to "Ubuntu" and thus act accordingly. I'm curious on any thoughts and potential risks this approach could come with, as I'm very keen on making use of such a tool. But I'm also very interested in which steps I could do manually or via different types of software, to find and install the correct (Pop OS optimized and verified) drivers that I'm lacking, without having to jeopardise my OS.

**Comment by tuxedo-ma** [comment]
Dear @davelbit,
Thank you for reaching out to the Tuxedo team and providing valuable feedback about your experience with the Infinitybook 16 Pro Gen-7 running Pop OS 22.04. We appreciate your enthusiasm and engagement with our products.

We understand your concerns regarding the potential absence of certain drivers impacting performance. While we appreciate your suggestion to add a workaround for Pop OS in the tuxedo-tomte script, we want to clarify our current position.

At this time, Tuxedo-Tomte is designed and tested to work seamlessly with our supported operating systems, and our focus has been on providing the best possible support for these systems. As you rightly pointed out, Pop OS is a Debian and Ubuntu derivative, and in theory, there should be compatibility. However, it's essential to note that our testing and quality assurance processes are tailored specifically for our supported systems.

We want to be transparent about our decision not to officially support Pop OS presently. Adding the suggested line to the Perl script could indeed be a potential workaround for users like yourself. However, it's crucial to consider that by doing so, we cannot guarantee the same level of stability, performance, and compatibility as with our supported systems.

Moreover, officially supporting Pop OS would require thorough testing and validation to ensure a reliable user experience. As of now, we don't have plans to extend support to Pop OS.

We understand that this may be disappointing for some users, and we appreciate your understanding of our position.

Thank you again for bringing this to our attention and for your continued support of Tuxedo products.

Best regards,
M. Arnold
