### ISSUE TITLE
tomte fails since last kernel update

### ISSUE THREAD

**Issue by kemlath** [tuxedocomputers/tuxedo-tomte#23]
On a Notebook TUXEDO InfinityBook S 17 - Gen6 running Ubuntu 20.04 LTS

Since the last kernel update tomte yields the following error message when called e.g.: 
tompte list
tomte: error:  no packages found matching plasma-workspace
 is not a valid version

uname -a 
Linux korcslayer-LINUX 5.15.0-10072-tuxedo #79~20.04.1tux1 SMP Fri May 5 15:33:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vinzv** [comment]
This has been fixed with today's update. Please run `apt upgrade` or update your system via package management.
