### ISSUE TITLE
Support for Ubuntu 23.04

### ISSUE THREAD

**Issue by stavros-k** [tuxedocomputers/tuxedo-tomte#25]
Hello, would it be possible to add support for Ubuntu 23.04?
Just got my InfinityBook Pro 14 Gen 8 and moved my drive from my old laptop!

**Comment by spiftire** [comment]
I would alos love support for Ubuntu 23.04 and 23.10 when it arrives

**Comment by tuxedo-ma** [comment]
Hello @stavros-k and @spiftire ,

Thank you for reaching out and congratulations on your new InfinityBook Pro 14 Gen 8!

We appreciate your interest in running Ubuntu 23.04 on your new laptop. However, our current support is focused on LTS (Long Term Support) versions of Ubuntu, specifically 20.04 and 22.04. We plan to extend support to 24.04 when it becomes available.

LTS versions provide a stable and well-tested platform, ensuring a reliable experience for our users. We understand that you might be excited to use the latest version, and we appreciate your enthusiasm. In the meantime, we recommend using one of our supported LTS versions for the best performance and compatibility.

If you have any further questions or if there's anything else we can assist you with, please feel free to let us know.

Best regards,
M. Arnold
