### ISSUE TITLE
Tuxedo Tomte Never Completes

### ISSUE THREAD

**Issue by pasetti** [tuxedocomputers/tuxedo-tomte#29]
I have a Tuxedo laptop with Ubuntu 20.04. It worked fine until yesterday. Today, after switching it on, I see the small pop-up at the top of the screen which says: "TUXEDO Tomte is installing fixed. Please do not restart or shutdown the system". The pop-up never disappears (and if I click on the cross in its upper right-hand corner, it disappears for a few seconds but then comes back). Also, the fan of the laptop is running at high speed all the time. 

After letting the system alone for about 20 minutes with no changes, I shut it and re-started it. The same behaviour appeared again.

Conclusion: the laptop is virtually unusable (owing to the noise of the fan). What should I do?

The screenshot below provides information about the system configuration.

![image](https://github.com/tuxedocomputers/tuxedo-tomte/assets/15838404/e22e8136-ccef-46ca-8819-117a7b64facd)

**Comment by FireMidge** [comment]
I don't have the fan noise, but I also keep getting this extremely annoying popup "TUXEDO Tomte is installing fixes. Please do not restart or shutdown the system" that you CANNOT close. As soon as you click on the X, a new, identical notification appears.

I also have been having this problem since yesterday and it is very annoying and distracting. Even when putting a film into full screen mode, the notification is still visible, blocking part of the screen. A restart does not help.

Please can this be fixed!

![image](https://github.com/tuxedocomputers/tuxedo-tomte/assets/4896496/1e9178fb-c311-4b69-a759-0343f348713e)
(^ Getting spammed with notifications. Even "Do Not Disturb" mode can't suppress this notification from popping up)

**Comment by FireMidge** [comment]
To anyone else who needs an immediate, hacky fix:
Settings (system settings) -> Notifications -> TUXEDO Control Center -> change ON to OFF. I still got another 2 notifications after that, but then it stopped. Means there won't be any notifications from Tuxedo any more, which isn't ideal, but better than this permanent box on top, covering up menu items and making it very difficult working in certain applications.

**Comment by mariakawula** [comment]
Same issue. Turning off the notifications is indeed helpful, but the fan is still loud. I hope this can be resolved soon.

**Comment by FireMidge** [comment]
This is what I received from Tuxedo support, which seems to have fixed the notification spamming for me, and may also help with the fan problems you are experiencing:

```
sudo apt-get purge tuxedo-tomte
sudo apt-get install tuxedo-tomte
sudo tomte reconfigure all
```

After that, a restart will be required.

**Comment by pasetti** [comment]
I confirm the procedure proposed by FireMidge in the previous post. However, when I tried the first command (`sudo apt-get purge tuxedo-tomte`), I had the following error:

`E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.`

I contacted again Tuzedo and their advised me to kill the tuxedo-tomte process which I eventually did with the following command: `sudo killall tuxedo-tomte`. I then proceeded with the commands listed in the previous post, namely:
```
sudo apt-get purge tuxedo-tomte
sudo apt-get install tuxedo-tomte
sudo tomte reconfigure all
```
All worked fine after a re-start.

**Comment by pasetti** [comment]
I would like to re-open this issue because I again have the continuous fan noise and the annoying notification box at the top of my screen ("TUXEDO Tomte is installing fixes ..."). If I close the box, it reappears again a few seconds later. As recommended in previous posts, I first tried: `sudo killall tuxedo-tomte.`. This stopped the fan. I then tried the following commands:

```
sudo apt-get purge tuxedo-tomte
sudo apt-get install tuxedo-tomte
sudo tomte reconfigure all
```

However, the first command fails with the following error:

`E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.`

How do I get rid of the error and how do I permanently fix the Tuxedo-Tomte error?

**Comment by towo2099** [comment]
Do, what your system is telling you:

`sudo dpkg --configure -a`

**Comment by Emohr-Tuxedo** [comment]
towo2099 is right, you can't install anything correctly while your package management database is broken.

Type it in your system and follow the instructions. Tomte will not be able to work properly on your system while something is broken.

**Comment by pasetti** [comment]
I confirm that running `sudo dpkg --configure -a` fixed the problem. I then ran the following commands (I had to do it twice and shortly after the command which kills the Tomte application):
```
sudo apt-get purge tuxedo-tomte
sudo apt-get install tuxedo-tomte
sudo tomte reconfigure all

```
Today, after having re-started the laptop, the problem is no longer present. I should finally add that I had already gone through the same procedure last December and the problem had remained absent until yesterday. I do not know why it re-appeared.

**Comment by Emohr-Tuxedo** [comment]
When Tomte sees a broken package management database, it tries to repair it by itself, but it does not always succeed, there might be different reasons for this, it works most of the time without anyone to be aware of it.

The real question is ... why does your database breaks at all. I am quite sure that it is not Tomte ... it does most of the time only checks without installing anything. You get a notification on your desktop in case Tomte has to install something that takes some more time, like a new Kernel or a new Nvidia driver.

I am just wildly guessing here now ... is it possible that you have automatic updates activated? and e.g. it is making an update and the update gets interrupted in a sudden way (power loss/cold reboot/etc.), then the database could get corrupted.
