### ISSUE TITLE
Option for blocking new modules 

### ISSUE THREAD

**Issue by salihmarangoz** [tuxedocomputers/tuxedo-tomte#3]
It is possible to add an option for blocking new modules being installed automatically:
$ sudo tuxedo-tomte block --new-modules
$ sudo tuxedo-tomte unblock --new-modules

Also, while installing the tuxedo-tomte, is it possible to prevent everything being installed with something like an environment variable:
$ TOMTE_DONT_INSTALL=1 sudo apt install tuxedo-tomte
or,
$ touch $HOME/.tuxedo_no_automatic_install; sudo apt install tuxedo-tomte
Afterwards tuxedo-tomte may delete the file and block new modules being installed.

These kind of features is needed I think, because there is no option for removing the modules. Some people may like things done automatically in the background but I always become afraid of what modifications will occur in my system. But I also would like to keep updated some modules and let tuxedo-tomte handle it.

**Comment by vinzv** [comment]
Hey there... thanks for the idea!
We recently discussed it internally and really want to implement it. So it's on our to-do list and will get implemented at some point later in time.

**Comment by tuxedo-ma** [comment]
Hi @salihmarangoz ,

Thank you for your valuable input and suggestion! We appreciate your interest in enhancing the functionality of tuxedo-tomte. It's fantastic that based on your proposal the feature was integrated.

As you may already know, we've introduced global modes like AUTOMATIC, UPDATES_ONLY, and DONT_CONFIGURE to offer users more control over the behavior of tuxedo-tomte. 

We understand the importance of providing users with flexibility and control over system modifications, and your suggestions aligned perfectly with that philosophy.

We appreciate your contribution and look forward to providing you with an even more robust and tailored tuxedo-tomte in the future.

If you have any more ideas or feedback, feel free to share them with us. We value your contributions to the improvement of our software.

Best regards,
M. Arnold
