### ISSUE TITLE
Support for Linux Mint 21.3

### ISSUE THREAD

**Issue by bobozaur** [tuxedocomputers/tuxedo-tomte#31]
Hello,

I opened #30 to introduce support of `Linux Mint 21.3` and would love to get it reviewed and merged so that I can rely on the main `tuxedo-tomte` package instead of having to keep a fork installed. This would most likely benefit other people too.

Thanks!

**Comment by tuxedo-ma** [comment]
Hi,

thank you for contributing to tuxedo-tomte.

Your fix seems right. We are in the process of testing functionality for Linux Mint 21.3 with tuxedo-tomte.

I am looking forward to add it into the next update of tuxedo-tomte. As a rough estimate I would say about a week from now.

Thank you very much and best wishes!

Maximilian Arnold

**Comment by tuxedo-ma** [comment]
Hi,

tuxedo-tomte now supports Linux Mint 21.3

Please continue contacting us by issue, if there are further suggestions.

Best wishes!

Maximilian Arnold
