### ISSUE TITLE
Error message for unsupported OS

### ISSUE THREAD

**Issue by FedericoCeratto** [tuxedocomputers/tuxedo-tomte#32]
Installing `tuxedo-tomte_2.28.0_all.deb` triggered a desktop notification:
`The version {version} of Debian GNU/Linux is not supported. `

(note the {version} placeholder without value)

**Comment by FedericoCeratto** [comment]
It appears `/usr/bin/tuxedo-tomte` is looking for `VERSION_ID` in `/etc/os-release` and not finding it.

**Comment by Emohr-Tuxedo** [comment]
Could you please post the content of /etc/os-release ?

**Comment by FedericoCeratto** [comment]
```
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by Emohr-Tuxedo** [comment]
Ah, there is the problem, no version of Debian is supported by Tomte. Sorry.

**Comment by FedericoCeratto** [comment]
It appears to support Ubuntu... anyhow perhaps the error message should be made more clear.

**Comment by Emohr-Tuxedo** [comment]
> The version {version} of Debian GNU/Linux is not supported.

Sorry, but what is not clear about this

**Comment by JonnieCache** [comment]
The sentence construction implies that a different version of debian would be supported.

**Comment by FedericoCeratto** [comment]
@JonnieCache yes, additionally `{version}` is a placeholder for a `version` variable, instead it's being printed out verbatim.

**Comment by Emohr-Tuxedo** [comment]
THX, I will change the message

**Comment by Emohr-Tuxedo** [comment]
Message has been changed, THX
