### ISSUE TITLE
Tuxedo-tomte with fault nvidiadriver install

### ISSUE THREAD

**Issue by Freemike123211** [tuxedocomputers/tuxedo-tomte#34]
I have installed tuxedo linux on my old PC. Every time after booting, tomte installed the latest nvidia driver, which does not support my old GeForce 730, a reboot is not possible afterwards. For now I uninstalled tomte, now everything works fine. Is this a tomte error? Is there a better solution?

**Comment by ykarrde** [comment]
According to the desciption:

> TUXEDO Tomte is a configuration service that automatically **recognizes the customer’s device** and checks for missing drivers or required packages...

https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/What-is-TUXEDO-Tomte-.tuxedo
I would say definitely a error.

But alternatively you should be able to configure the tomte modules (separately) and block only everything that you do not want, or not need.

Basically, in this case: 
`sudo tuxedo-tomte block nvidia-driver`
Should stop tomte from updating the nvidia driver (what I am doing currently), you can still use the driver you have installed it just blocks the update.

**Comment by Emohr-Tuxedo** [comment]
If you want to install the newest Tomte version, then you could create a file _/etc/tomte/DONT_CONFIGURE_ **before** installing Tomte.
As the manpage says:

> DONT_CONFIGURE
>               Nothing will be configured by Tomte.
> 
>        Usefull  if you want to create the file before installing Tomte to avoid Tomte to make any unwanted changes to the
>        system or to set Tomte on hold after having the configuration you want.
> 
> POSSIBLE WORKFLOW
> If you don't want Tomte to make any modifications on your system or you want to keep your specific kernel, you
>            could create the file DONT_CONFIGURE in /etc/tomte/ and Tomte will not make any modifications on  the  system,
>            except for the required repositories and Debian mirrors.
> 
>            Afterwards you could list the required fixes with
>                         tomte list
>            block the fixes you don't want on your system with
>                         sudo tomte block <MODULE>
>            and set the Tomte installation mode to AUTOMATIC or UPDATES_ONLY with
>                         sudo tomte AUTOMATIC
>            or
>                         sudo tomte UPDATES_ONLY
>            Alternatively you could install the fixes you want manually by using
>                         sudo tomte configure <MODULE>

**Comment by Freemike123211** [comment]
Thanks, it works 😉

**Comment by Emohr-Tuxedo** [comment]
You're welcome :thumbsup:
