### ISSUE TITLE
Ubuntu 24.04 Support?

### ISSUE THREAD

**Issue by MasterRoCcO** [tuxedocomputers/tuxedo-tomte#36]
Wie sieht es mit der Unterstützung von Ubuntu 24.04 aus?

What about Ubuntu 24.04 support?

**Comment by Emohr-Tuxedo** [comment]
We are working on it, should be ready in a few weeks.

**Comment by stkr22** [comment]
Just switched to 24.04. Any updates on this one?

**Comment by Emohr-Tuxedo** [comment]
I just can say that we are working hard on this, there are still some problems and we are still figuring out whether we can solve it with some kernel patches or some other way.

Anyway, we will not release 24.04 if our testing is not successful and that takes some time. Sorry.

**Comment by Emohr-Tuxedo** [comment]
Issue can be closed as support for 24.04 has been implemented.

THX for waiting

**Comment by nerdoc** [comment]
Is this also true for KDE neon (24.04 noble)? Because My installation of tomte 2.40.2 does not work. Since installation, I always get the errors at every install of any package:
```
Consult /var/lib/dkms/tuxedo-drivers/4.11.7/build/make.log for more information.
dpkg: Fehler beim Bearbeiten des Paketes tuxedo-drivers (--configure):
 »installiertes post-installation-Skript des Paketes tuxedo-drivers«-Unterprozess gab den Fehlerwert 10 zurück
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von tuxedo-control-center:
 tuxedo-control-center hängt ab von tuxedo-drivers (>= 4.0.0) | tuxedo-keyboard (>= 3.1.2); aber:
  Paket tuxedo-drivers ist noch nicht konfiguriert.
  Paket tuxedo-keyboard ist nicht installiert.
  Paket tuxedo-drivers, das tuxedo-keyboard bereitstellt, ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten des Paketes tuxedo-control-center (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für hicolor-icon-theme (0.17-2) werden verarbeitet ...
Trigger für man-db (2.12.0-4build2) werden verarbeitet ...
Not building database; man-db/auto-update is not 'true'.
Trigger für desktop-file-utils (0.27-2build1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 tuxedo-drivers
 tuxedo-control-center
E: Sub-process /usr/bin/dpkg returned an error
```
This basically is not a direct problem of tomte, but of the packages it tries to install

**Comment by Emohr-Tuxedo** [comment]
@nerdoc

I moved your comment to another issue as it is a separate problem: https://github.com/tuxedocomputers/tuxedo-tomte/issues/49
