### ISSUE TITLE
Double negative in German status message

### ISSUE THREAD

**Issue by linuxundich** [tuxedocomputers/tuxedo-tomte#38]
Tomte reports

> Bitte starten Sie das System nicht neu oder fahren Sie es nicht herunter.

that's a double negative. It should say

> Bitte führen Sie keinen Neustart des Systems durch und fahren Sie es nicht herunter.

![Screenshot_20240529_155122](https://github.com/tuxedocomputers/tuxedo-tomte/assets/1716643/34abd7c3-8a93-4b90-8cbe-5cd689d8a28e)

**Comment by Emohr-Tuxedo** [comment]
Thank you, I will change the text.

**Comment by Emohr-Tuxedo** [comment]
The issue can be closed as it has been implemented in the current release
