### ISSUE TITLE
Is this compatible with non-debian distros?

### ISSUE THREAD

**Issue by ghost** [tuxedocomputers/tuxedo-tomte#4]
I'm considering purchasing a tuxedo laptop and testing non-debian distros on it (fedora, opensuse, nixos, deepin). Is there a chance of this working on them?

**Comment by vinzv** [comment]
Hi there,

no, unfortunately it is not. We simply have to focus on a few distributions to be supported.
Sorry for that. :-/

Still you can try to run fixes (if they are necessary!) yourself by having a look into the source code:
https://github.com/tuxedocomputers/tuxedo-tomte/blob/master/src/tuxedo-tomte
