### ISSUE TITLE
Kubuntu 24.04 installation of fixes failed

### ISSUE THREAD

**Issue by RalfZim** [tuxedocomputers/tuxedo-tomte#40]
I just did a fresh install of Kubuntu 24.04 on my Tuxedo InfinityBook Pro 14 v4.
I then installed tuxedo-tomte which then ran automatically.
Later on, when I open a terminal and type "tuxedo-tomte list", I get the following output:

> Selected installation mode: AUTOMATIC
Only showing fixes that are available for this hardware
Name                               Version  Installed  Blocked      Required
apport-fix                         2        yes        no           yes
linux-tuxedo-24.04                 1        yes        no           yes
tuxedo-control-center              1        failed     no           yes
tuxedo-drivers                     1        failed     no           yes
tuxedo-mirrors                     5        yes        no           yes
tuxedo-repos                       4        yes        no           prerequisite

Why do I have those **two failed entries**?
What can I do to fix this?

**Comment by Emohr-Tuxedo** [comment]
Hi, those two are packages, it might be that your local package management got blocked by some other application. I would advice to restart the system and see whether Tomte manages to install those packages.

**Comment by RalfZim** [comment]
After a few restarts, it actually looks fine. Thank you for your quick response!

**Comment by Emohr-Tuxedo** [comment]
I'am glad I could help you!
