### ISSUE TITLE
Long boot times after upgrade to Ubuntu 24.04.1

### ISSUE THREAD

**Issue by circleape** [tuxedocomputers/tuxedo-tomte#42]
Hi, I don't know if the issue is with tuxedo-tomte, but based on the results below I suspect it may be:

$ systemd-analyze blame
21.674s plymouth-quit-wait.service
 7.608s tuxedo-tomte.service
 4.917s NetworkManager-wait-online.service
 1.441s fwupd.service
  917ms NetworkManager.service
  822ms snapd.seeded.service
  690ms snapd.service

I read somewhere that plymouth isn't necessarily causing delays, but it sits there in parallel and this is its runtime.

The symptom: After pressing the power on button on my InfinityBook Pro 14 Gen6, it takes about 30 seconds for the Tuxedo logo to appear, then it stays like that for about 15 seconds and only then I am prompted to enter the password to decrypt the drive.

This started happening after the upgrade to Ubuntu 24.04.1. Before, instead of about 30+15 seconds of waiting it was about 10.

Any ideas? Thanks in advance.

**Comment by Emohr-Tuxedo** [comment]
Hi, this has MOST probably nothing to do with Tomte.

Tomte is very unobstructive and there are no services waiting for Tomte to finish. Tomte uses those 7.6 seconds most probably waiting for a network connection and doing an 'apt update' to check for new fixes. It is probably waiting 95% of that time for 'apt update' to complete. This has nothing to do with the start or delay of the rest of the system as it runs parallel to the other services.

**Comment by circleape** [comment]
Hi, thanks for the clarification. Do you know how to check what is actually causing the delay?

I ran sudo systemd-analyze now and it resulted in:
Startup finished in 28.727s (firmware) + 2.429s (loader) + 15.471s (kernel) + 24.601s (userspace) = 1min 11.229s 
graphical.target reached after 24.566s in userspace.

**Comment by Emohr-Tuxedo** [comment]
Sorry for the late answer.

I can't help you. The topic is complex and there are different ways to find out what's causing the delay.

In my opinion that goes beyond the scope of Tomte related topics.
