### ISSUE TITLE
Infinite loop in `isTextInFile`

### ISSUE THREAD

**Issue by jfschaefer** [tuxedocomputers/tuxedo-tomte#44]
`perl -w /usr/bin/tuxedo-tomte configure all` ran for me with 100% CPU usage.

I've been digging a bit into the code and the problem seems to be the `while` loop in `isTextInFile`.

Specifically, adding a line for logging:
```perl
		while( $FH ) {
			printLog("FILE $filename MATCH /$match/", 'TL0', '[WARN]');
			if ( $_ =~ /$match/sm) {
				return (1);
			}
		}
```
I get the following output:
```
FILE /etc/modprobe.d/tuxedo_early_load_backlight_control_fix.conf MATCH /softdep nvidia pre: i915/
FILE /etc/modprobe.d/tuxedo_early_load_backlight_control_fix.conf MATCH /softdep nvidia pre: i915/
FILE /etc/modprobe.d/tuxedo_early_load_backlight_control_fix.conf MATCH /softdep nvidia pre: i915/
FILE /etc/modprobe.d/tuxedo_early_load_backlight_control_fix.conf MATCH /softdep nvidia pre: i915/
```
etc.

`/etc/modprobe.d/tuxedo_early_load_backlight_control_fix.conf` contains a single line:
```
softdep nvidia pre: i915
```

I feel like this should be an easy fix, but I don't know any perl, unfortunately.

**Comment by jfschaefer** [comment]
Okay, https://github.com/tuxedocomputers/tuxedo-tomte/pull/43 seems to fix it

**Comment by Emohr-Tuxedo** [comment]
THX, I will correct it and upload it today

**Comment by Emohr-Tuxedo** [comment]
The hotfix is online. Please update Tomte and you might want to delete the logfile:

`sudo rm /var/log/tomte/tomte.log`

THX again for letting me know

**Comment by jfschaefer** [comment]
Great, the new version works.
And thanks for mentioning that the log file should be removed (it was 23GB).
