### ISSUE TITLE
"tomte list" and "tomte versions" crashes

### ISSUE THREAD

**Issue by ogrman** [tuxedocomputers/tuxedo-tomte#45]
This issue appeared suddenly, when running `tomte list` and `tomte versions`:

```
tomte: error:  is not a valid version
```

Note the double space there. I'm not getting anything in the `/var/log/tomte/tomte.log` file for these runs, but I do see this in the log file:

```
[ERROR] 20240921 09:41:52 could not open file 0 No such file or directory
```

This is my `/etc/tomte/modules.cfg`:

```
# name version installed blocked required hwid
gfxmode 1 yes no yes 1
linux-tuxedo-22.04 1 yes no yes 1
no-keyboard-after-suspend-fix 2 yes no yes 5
nvidia-driver 7 yes no yes 1
text-boot 1 no yes yes 1
tuxedo-control-center 1 yes no yes 1
tuxedo-dgpu-run 1 yes no yes 1
tuxedo-drivers 1 yes no yes 1
tuxedo-mirrors 5 yes no yes 1
tuxedo-repos 4 yes no prerequisite 1
tuxedo-touchpad-switch 1 yes no yes 1
```

There is not `/etc/tomte/AUTOMATIC`, `/etc/tomte/DONT_CONFIGURE` or `/etc/tomte/UPDATES_ONLY` files, which I assume to mean that it will use the default `AUTOMATIC` mode.

I'm on a TUXEDO Stellaris 16 - Gen5 - AMD, it's running the Tuxedo OS that was pre-installed on the computer. It seems like `tomte` still manages to update drivers, since it upgraded to the new nvidia driver after this issue started. Let me know if there is any more info you desire.

**Comment by Emohr-Tuxedo** [comment]
Mmmh, that's really weird ...

THX, I will check this out.

**Comment by lera34** [comment]
I have the same problem. But command will work with `sudo`.

**Comment by Emohr-Tuxedo** [comment]
Thanks to everyone, the new Tomte version 2.39.2 should fix that problem. It is online.

You just have to update Tomte:

```
sudo apt update
sudo apt install tuxedo-tomte
```
