### ISSUE TITLE
Unattended Upgrades Shutdown

### ISSUE THREAD

**Issue by gzuuus** [tuxedocomputers/tuxedo-tomte#46]
There is a very uncomfortable behaviour that I sometimes notice after upgrades that shut down my tuxedo computer without notifying beforehand, it just shut down and restarts. It happens to me various times when I was working and really doesn't feel good to lost your work. I have narrowed some logs
```
~cat /var/log/syslog | grep -i "shutdown"
systemd[1]: Starting Create final runtime dir for shutdown pivot root...
systemd[1]: Finished Create final runtime dir for shutdown pivot root.
systemd[1]: Starting Record System Boot/Shutdown in UTMP...
systemd[1]: Finished Record System Boot/Shutdown in UTMP.
systemd[1]: Started Unattended Upgrades Shutdown.
containerd[1024]: time="2024-10-05T12:08:53.464021750+02:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
systemd[1186]: Reached target Shutdown.
```
I don't know if it's related to this, but I couldn't find other related logs, I'm new with tuxedo computers, so I would appreciate any guidance

**Comment by Emohr-Tuxedo** [comment]
I am sorry, this has nothing to do with Tomte. Unattended upgrades is a feature that exists independently.

You might want to check https://help.ubuntu.com/community/AutomaticSecurityUpdates or this https://askubuntu.com/questions/1186492/terminate-unattended-upgrades-or-whatever-is-using-apt-in-ubuntu-18-04-or-later to configure or remove it.

**Comment by gzuuus** [comment]
Thanks! unattended-upgrades is v poorly design, didn't know such a bad pos were distributed across ubuntu distros. Thanks for pointing out
