### ISSUE TITLE
Package signature?

### ISSUE THREAD

**Issue by sualko** [tuxedocomputers/tuxedo-tomte#6]
Hi everyone,

the [installation guide](https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/What-is-TUXEDO-Tomte-.tuxedo) recommends to install from http://deb.tuxedocomputers.com/ubuntu/pool/main/t/tuxedo-tomte/, but I wonder if there is any signature we could verify. If there is no signature, please at least change the link to a secure connection.

Cheers,
Klaus

**Comment by vinzv** [comment]
Just changed the installation guide. Thanks for pointing out!
