### ISSUE TITLE
[BUG] Latest release makes the screen flicker

### ISSUE THREAD

**Issue by tomasnorre** [tuxedocomputers/tuxedo-tomte#9]
Hi. 

The latest update, with `tuxedo-tomte`, gave me problems on my `TUXEDO InfinityBook Pro 14 Gen6 Standard` This is causes my screen to flicker, and make my laptop useless. 

```diff 
-tuxedo-tomte 2.5.21 all
+tuxedo-tomte 2.5.25 all
``` 

I have located it to here: 
https://github.com/tuxedocomputers/tuxedo-tomte/blob/4d163225d34fc33223237bc46f656fb1be685f91/src/tuxedo-tomte#L3857

The Tuxedo Website, suggests the change that this script is overriding. So I'm a little confused. 
https://www.tuxedocomputers.com/en/Infos/Help-Support/Help-for-my-device/TUXEDO-InfinityBook-Series/TUXEDO-InfinityBook-Pro-14/Fix-flickering-display-after-manualy-installing-an-OS.tuxedo

If I set my grub config back, the screen stops flickering, at least as long as there is an external monitor connection. The second I reboot my laptop, the grub setting is set back to what suggestion in the tuxedo-tomte. 

I really hope for a fast fix, as this makes my laptop useless. 

The apt-package manager only allows me to install the latest version, doesn't find other version available, so hard to do a rollback 

```shell 
$ apt search tuxedo-tomte
Sorting... Done
Full Text Search... Done
tuxedo-tomte/unknown,unknown,now 2.5.25 all [installed]
  little helper that provides services, updates and fixes for TUXEDO devices
```

**Comment by tomasnorre** [comment]
Just read on the website 
https://www.tuxedocomputers.com/en/Infos/Help-Support/Frequently-asked-questions/What-is-TUXEDO-Tomte-.tuxedo

> The user settings are not overwritten.

This is not quite true, every time I reboot, my `/etc/default/grub` file gets adjusted.

**Comment by akikoskinen** [comment]
I'm hit with this too. My laptop screen is effectively useless now. The only way to use the computer is with an external monitor.

I modified the boot parameters manually, replacing the odd `i915.tuxedo_disable_psr2=1` with `i915.enable_psr=0`. This fixed the laptop screen after one reboot, but after another reboot the boot parameter was automatically reset and the laptop screen was flickering like hell again.

This needs a quick fix or tomte has to be uninstalled.

**Comment by tomasnorre** [comment]
Thanks for confirming. I'm still trying to see if the tomte.cfg can be modified, to not do this. But still not really familiar with it.

**Comment by abdulmateen59** [comment]
I have the same problem with my POLARIS 15, since the day I bought it, changing the kernel parameters fixes the problem after a reboot, but after another reboot, it starts flickering again. I am really annoyed.

**Comment by circleape** [comment]
I also had this problem with the latest tomte in my InfinityBook Pro 14 Gen6. Support told me to do the following and it worked:

Please switch to the terminal with CTRL+ALT+F2 and log in with your user name & password. Execute the following commands and enter your user password:

`sudo apt update && sudo apt -y upgrade && sudo tuxedo-tomte reconfigure all`

If this step was successful, the system can be rebooted via

`reboot`

**Comment by tomasnorre** [comment]
> `sudo apt update && sudo apt -y upgrade && sudo tuxedo-tomte reconfigure all`
> If this step was successful, the system can be rebooted via
> `reboot`

I can confirm that this is working on the `TUXEDO InfinityBook Pro 14 Gen6 Standard`

**Comment by vinzv** [comment]
Thanks for the bug report! 
We'll have a look at it and therefore, to avoid duplicate communication, close your support ticket.

**Comment by tomasnorre** [comment]
Thanks for taking care. As you see from my communication, I got to it step by step. Next time I'll try to collect all infos at once and not spam your support system.
